#! /bin/bash -

MMU=Processor/VMSAv6
SYSTEM=Tests/Blink

CFLAGS="-I . -Wall -nostartfiles -nostdlib -fno-zero-initialized-in-bss -static -march=armv8-a+nofp -O4 -I $MMU -I $SYSTEM"
CFLAGS="$CFLAGS $*"
echo $CFLAGS

arm-none-eabi-gcc-9.2.1 \
        -c \
        Processor/CortexA53/processor.c \
        $MMU/mmu.c \
        --no-toplevel-reorder \
        $CFLAGS &&
arm-none-eabi-objcopy --rename-section .text=.init --rename-section .data=.init.data processor.o processor.boot &&
arm-none-eabi-objcopy --rename-section .text=.init --rename-section .data=.init.data mmu.o mmu.boot &&

arm-none-eabi-gcc-9.2.1 \
        processor.boot mmu.boot \
        $SYSTEM/*.c \
        -o kernel7.elf \
        $CFLAGS \
        -Wl,--defsym=top_of_boot_RAM=0x1000000 \
        -Wl,--defsym=translation_table=0xfff80000 \
        -Wl,--defsym=global_translation_table=0xfff84000 \
        -Wl,--defsym=local_kernel_page_table=0xfff88000 \
        -Wl,--defsym=global_kernel_page_tables=0xfff89000 \
        -Wl,--defsym=shared=0xfffe0000 \
        -Wl,--defsym=workspace=0xfffd0000 \
        -Wl,--section-start=.init=0xfc000000 \
        -Wl,--section-start=.text=0xfc001000 &&
arm-none-eabi-objcopy -R .ignoring -O binary kernel7.elf kernel7.img &&
arm-none-eabi-objdump -x --disassemble-all kernel7.elf > kernel7.dump
