#! /bin/bash -

SYSTEM=$( dirname $0 )
SUBSYSTEMS=RawMemory:OSTask:SimpleHeap

echo Building system $SYSTEM with ${SUBSYSTEMS//:/ }

MMU=Processor/VMSAv6

CFLAGS="-I . -Wall -nostartfiles -nostdlib -fno-zero-initialized-in-bss -static -march=armv8-a+nofp -O4 -I Processor -I $MMU -I $SYSTEM -I Utilities -I Devices"
CFLAGS="$CFLAGS -I ${SUBSYSTEMS//:/ -I }"
CFLAGS="$CFLAGS $*"
echo $CFLAGS

arm-none-eabi-gcc-9.2.1 \
        -c \
        Processor/CortexA53/processor.c \
        $MMU/mmu.c \
        --no-toplevel-reorder \
        $CFLAGS &&
arm-none-eabi-objcopy --rename-section .text=.init --rename-section .data=.init processor.o processor.boot &&
arm-none-eabi-objcopy --rename-section .text=.init --rename-section .data=.init mmu.o mmu.boot &&

SOURCES="$SYSTEM:$SUBSYSTEMS:"

echo Sources: ${SOURCES//://*.c } &&

# 16MiB boot RAM
# 256MiB minimum RAM
arm-none-eabi-gcc-9.2.1 \
        processor.boot mmu.boot \
        ${SOURCES//://*.c } \
        romimage_end.c \
        -o kernel7.elf \
        $CFLAGS \
        -Wl,--defsym=top_of_boot_RAM=0x1000000 \
        -Wl,--defsym=top_of_minimum_RAM=0x10000000 \
        \
        -Wl,--defsym=OSTask_free_pool=0xff100000 \
        -Wl,--defsym=OSTaskSlot_free_pool=0xff200000 \
        -Wl,--defsym=VMSAv6_Level2_Tables=0xff300000 \
        -Wl,--defsym=system_heap_base=0xff400000 \
        -Wl,--defsym=system_heap_top=0xff500000 \
        -Wl,--defsym=shared_heap_base=0xff500000 \
        -Wl,--defsym=shared_heap_top=0xff600000 \
        \
        -Wl,--defsym=log_pipe=0xfff00000 \
        -Wl,--defsym=log_pipe_top=0xfff02000 \
        -Wl,--defsym=app_memory_limit=0x40000000 \
        -Wl,--defsym=pipes_base=0x80000000 \
        -Wl,--defsym=pipes_top=0xc0000000 \
        \
        -Wl,--defsym=OSTask_free_pool=0xff100000 \
        -Wl,--defsym=OSTaskSlot_free_pool=0xff200000 \
        \
        -Wl,--defsym=OSQueue_free_pool=0xfff90000 \
        -Wl,--defsym=OSPipe_free_pool=0xfffa0000 \
        \
        -Wl,--defsym=translation_table=0xfff80000 \
        -Wl,--defsym=global_translation_table=0xfff84000 \
        -Wl,--defsym=local_kernel_page_table=0xfff88000 \
        -Wl,--defsym=global_kernel_page_tables=0xfff89000 \
        -Wl,--defsym=workspace=0xfffd0000 \
        -Wl,--defsym=shared=0xfffe0000 \
        -Wl,--section-start=.init=0xfc000000 \
        -Wl,--section-start=.text=0xfc004000 &&
arm-none-eabi-objcopy -R .ignoring -O binary kernel7.elf kernel7.img &&
arm-none-eabi-objdump -x --disassemble-all kernel7.elf > kernel7.dump
